# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Programme Schedule
    url: /#solutions
    weight: 20
  - name: Registration Fees
    url: /Registration Fees
    weight: 30
  - name: Registration Page
    weight: 40
    hasChildren: true
  - parent: Module Coordinators
    name: Profiles
    url: post/
